<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-05-13T18:40:42 IST" name="Default suite" finished-at="2024-05-13T18:40:59 IST" duration-ms="17077">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:parallel.FailedRun@5032714f]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2024-05-13T18:40:42 IST" name="Default test" finished-at="2024-05-13T18:40:59 IST" duration-ms="17077">
      <class name="parallel.FailedRun">
        <test-method is-config="true" signature="setUpClass()[pri:0, instance:parallel.FailedRun@5032714f]" started-at="2024-05-13T18:40:42 IST" name="setUpClass" finished-at="2024-05-13T18:40:42 IST" duration-ms="384" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:parallel.FailedRun@5032714f]" started-at="2024-05-13T18:40:42 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-05-13T18:40:57 IST" duration-ms="14665" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Failed sceanrio"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Optional[To check failed scenario]"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
at parallel.TestFailedScenarioStep.check_the_arithmetic_expression(TestFailedScenarioStep.java:12)
at âœ½.check the arithmetic expression(file:///C:/Users/balaji.d/eclipse-workspace/CucumberPOMSeries/src/test/resources/parallel/TestFailedScenario.feature:3)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:parallel.FailedRun@5032714f]" started-at="2024-05-13T18:40:57 IST" name="tearDownClass" finished-at="2024-05-13T18:40:59 IST" duration-ms="1987" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- parallel.FailedRun -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
